package com.bhoomibot.os.feature.autonomous.execution

import com.bhoomibot.os.feature.autonomous.core.AgentOSManager
import com.bhoomibot.sdk.TaskPlan
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update

/**
 * PlanExecutionEngine: Runs the high-level TaskPlan generated by the AI Brain.
 */
class PlanExecutionEngine(
    private val agentOS: AgentOSManager,
    private val scope: CoroutineScope = CoroutineScope(Dispatchers.Main + SupervisorJob())
) {
    private val _uiState = MutableStateFlow(ExecutionState())
    val uiState = _uiState.asStateFlow()

    private var executionJob: Job? = null

    fun execute(plan: TaskPlan) {
        executionJob?.cancel()
        executionJob = scope.launch {
            _uiState.update { it.copy(isActive = true, currentStepIndex = 0, totalSteps = plan.steps.size) }
            
            plan.steps.forEachIndexed { index, step ->
                _uiState.update { it.copy(currentStepIndex = index, currentStepLabel = "${step.skillId} ${step.parameters}") }
                
                // L3: Skill Execution -> Trajectory
                val trajectory = agentOS.skills.executeSkill(step)
                
                // L7: Control Loop (Simplified for now)
                runControlLoop(trajectory)
                
                // Simulate step completion
                delay(2000) 
            }
            
            _uiState.update { it.copy(isActive = false, currentStepLabel = "Plan Completed") }
        }
    }

    private suspend fun runControlLoop(trajectory: com.bhoomibot.sdk.Trajectory) {
        // Here we would collect localization and send to control layer
        // For now, we just simulate the time it takes to follow a trajectory
        if (trajectory.waypoints.isNotEmpty()) {
            delay(3000) 
        }
    }

    fun stop() {
        executionJob?.cancel()
        _uiState.update { it.copy(isActive = false, currentStepLabel = "Execution Stopped") }
    }
}

data class ExecutionState(
    val isActive: Boolean = false,
    val currentStepIndex: Int = 0,
    val totalSteps: Int = 0,
    val currentStepLabel: String = "Idle"
)
