[project]
name = bhoomibot-esp32
version = 1.0
board = esp32c3

[build]
type = release
speed = 2

[lib]
dirs = lib

[env]
autoconfig = false

[platform]
espressif-esp32c3 = espressif32

[monitor]
autoconnect = false

[test]
enable = false

[monitor-device]
port = /dev/ttyUSB0

[build-single]
enable = false

[discovery]
enable = false

[logger]
level = info